"""init

Revision ID: 1c566f813fe9
Revises:
Create Date: 2025-03-10 21:05:11.533812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c566f813fe9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=200), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('last_login_date', sa.DateTime(), nullable=True),
    sa.Column('email', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('projects',
    sa.Column('id', sa.String(length=200), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('funding_program', sa.String(length=100), nullable=True),
    sa.Column('funding_amount', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('project_milestones',
    sa.Column('id', sa.String(length=200), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('start_week', sa.Integer(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('dependent_milestone_id', sa.String(length=200), nullable=True),
    sa.Column('project_id', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_roles',
    sa.Column('id', sa.String(length=200), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('hourly_rate', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=20), nullable=False),
    sa.Column('project_id', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_assumptions',
    sa.Column('id', sa.String(length=200), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('milestone_id', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['milestone_id'], ['project_milestones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_milestone_acceptance_criteria',
    sa.Column('id', sa.String(length=200), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('milestone_id', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['milestone_id'], ['project_milestones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_milestone_tasks',
    sa.Column('id', sa.String(length=200), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('hours_estimated', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.String(length=200), nullable=True),
    sa.Column('milestone_id', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['milestone_id'], ['project_milestones.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['project_roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_milestone_tasks')
    op.drop_table('project_milestone_acceptance_criteria')
    op.drop_table('project_assumptions')
    op.drop_table('project_roles')
    op.drop_table('project_milestones')
    op.drop_table('projects')
    op.drop_table('users')
    # ### end Alembic commands ###